apiVersion: v1
kind: Service
metadata:
  name: sts-svc
  labels:
    app: sts-svc-app
spec:
  ports:
  - port: 33001
    name: sts-tester-tcp
  clusterIP: None
  selector:
    app: sts-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-tester-tcp
spec:
  selector:
    matchLabels:
      app: sts-app # has to match .spec.template.metadata.labels
  serviceName: "sts-svc"
  replicas: 3 
  template:
    metadata:
      labels:
        app: sts-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sts-tcp-con
        image: "quay.io/sriramsrinivasan/inspector-utils:v1"
        imagePullPolicy: "IfNotPresent"
        command: ["nc"]
        args: ["-vkl","33001"]
        ports:
        - containerPort: 33001
          name: sts-tester-tcp
